import './globals.css'
import { Inter } from 'next/font/google'
import {Link} from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Quarta Entrega',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}
      <header className= "bg-gray-700 text-white">
        <h2>Meus Produtos</h2>
        <ul>
          <li className='inline'><Link href="/" >HOME</Link></li>
          <li className='inline'><Link href="/produtos/tenis" >Tênis</Link></li>
          <li className='inline'><Link href="/produtos/camisa" >Camisa</Link></li>
          <li className='inline'><Link href="/produtos/meia" >Meia</Link></li>
          <li className='inline'><Link href="/produtos/calca" >Calça</Link></li>
        </ul>
        </header>
      </body>
    </html>
    
  )
}
